title: ASM MD-Staff Documentation
description: API Documentation for MD-Staff Query Endpoints and Webhooks
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude the converter and HTML files
exclude:
  - html_to_markdown_converter.py
  - "*.html"
  - "*_files/"