title: ASM MD-Staff Documentation
description: API Documentation for MD-Staff Query Endpoints and Webhooks
# theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight
# plugins:
  # - jekyll-remote-theme

# Exclude the converter and HTML files
exclude:
  - html_to_markdown_converter.py
  - "*.html"
  - "*_files/"